### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-html-semantic-elements-5BSgA-#1]
## Create a "Products" page for a fake online store

@KatieMFritz Can you take a look at this? It's [hosted here](https://GriffinMartin.github.io/MI-449-SS17-740-html-semantic-elements-5BSgA-/) and meets the following criteria:

- [x] Place a `nav` element at the top of the page that includes (fake) links to other pages
- [x] Use the `main` element appropriately
- [x] Include three products your store sells, all listed on the same Products page
- [x] For each product, correctly use an `article`, `header`, and `footer` element
- [x] Use `figure` and `figcaption` to show what each product looks like
- [x] Each product includes a `nav` element with one or more links to related products (the links don't have to go anywhere)
- [x] Use an `aside` in one or more products to advertise a promotion or discount for that product

**Comment by KatieMFritz** [comment]
Nice job on this! 😁 🌞 I enjoyed your captions and related products - "All your roommates will soon hate you." 😆 

There are only two things I would change:

In your footer nav for each `article`, you have the navigation heading outside the `nav` element. I'd argue it belongs _inside_, because it only makes sense in the context of that `nav`. 
```html    
<!-- what you have  -->
       <footer>
          <h4>Related Products</h4>
          <nav>
            <ul>
              <li><a href="#">Coffee</a></li>
              <li><a href="#">Teapot</a></li>
            </ul>
          </nav>
        </footer>
```

I would also use `h2` instead of `h3` for the titles of your `article` elements, and `h3` for things within each article like `aside` and `nav`. While semantics are this are evolving (I can send you some links if you're interested), it's still best practice to go in order with your headings and not skip levels. You're creating an outline of your page with your `h1`-`h6` headings, and jumping around/skipping levels makes a spotty outline. Does that make sense?

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by GriffinMartin** [comment]
@KatieMFritz Thanks for the feedback and tips!
I fixed it up I think :)
My allergies are really bad so I'm squinting lol. Hopefully I didn't miss anything

**Comment by KatieMFritz** [comment]
Nice job! 🦑 🌴 🌟 ✨ 🍵 

:shipit:
